const languages = [
    {"country":"Afeganistão", "language":"Pastó", "word":"ترنس جنس"},
    {"country":"África do Sul", "language":"Zulu", "word":"i-transgender"},
    {"country":"Alemanha", "language":"Alemão", "word":"Transgender"},
    {"country":"Arábia Saudita", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Argentina", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Austrália", "language":"Inglês", "word":"Transgender"},
    {"country":"Áustria", "language":"Alemão", "word":"Transgender"},
    {"country":"Bangladesh", "language":"Bengali", "word":"ট্রান্সজেন্ডার"},
    {"country":"Bélgica", "language":"Neerlandês", "word":"Transgender"},
    {"country":"Bolívia", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Brasil", "language":"Português", "word":"Transexual"},
    {"country":"Canadá", "language":"Inglês", "word":"Transgender"},
    {"country":"Chile", "language":"Espanhol", "word":"Transgénero"},
    {"country":"China", "language":"Mandarim", "word":"变性人"},
    {"country":"Colômbia", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Coreia do Sul", "language":"Coreano", "word":"트랜스젠더"},
    {"country":"Costa Rica", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Cuba", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Dinamarca", "language":"Dinamarquês", "word":"Transkønnet"},
    {"country":"Egito", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Emirados Árabes", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Equador", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Espanha", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Estados Unidos", "language":"Inglês", "word":"Transgender"},
    {"country":"Filipinas", "language":"Filipino", "word":"Transgender"},
    {"country":"Finlândia", "language":"Finlandês", "word":"Transsukupuolinen"},
    {"country":"França", "language":"Francês", "word":"Transgenre"},
    {"country":"Grécia", "language":"Grego", "word":"τρανσέξουαλ"},
    {"country":"Guatemala", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Honduras", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Hungria", "language":"Húngaro", "word":"Transznemű"},
    {"country":"Índia", "language":"Hindi", "word":"ट्रांसजेंडर"},
    {"country":"Indonésia", "language":"Indonésio", "word":"Transgender"},
    {"country":"Irã", "language":"Persa", "word":"ترنس سکشوال"},
    {"country":"Iraque", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Irlanda", "language":"Inglês", "word":"Transgender"},
    {"country":"Islândia", "language":"Islandês", "word":"Transgender"},
    {"country":"Israel", "language":"Hebraico", "word":"טראנסג'נדר"},
    {"country":"Itália", "language":"Italiano", "word":"Transgender"},
    {"country":"Japão", "language":"Japonês", "word":"トランスジェンダー"},
    {"country":"Jordânia", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Kuwait", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Líbano", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Líbia", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Malásia", "language":"Malaio", "word":"Transgender"},
    {"country":"Marrocos", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"México", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Moçambique", "language":"Português", "word":"Transexual"},
    {"country":"Nepal", "language":"Nepali", "word":"ट्रान्सजेंडर"},
    {"country":"Nigéria", "language":"Inglês", "word":"Transgender"},
    {"country":"Noruega", "language":"Norueguês", "word":"Transkjønnet"},
    {"country":"Nova Zelândia", "language":"Inglês", "word":"Transgender"},
    {"country":"Países Baixos", "language":"Neerlandês", "word":"Transgender"},
    {"country":"Paquistão", "language":"Urdu", "word":"خواجہ سرا"},
    {"country":"Paraguai", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Peru", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Polônia", "language":"Polonês", "word":"Transpłciowy"},
    {"country":"Portugal", "language":"Português", "word":"Transexual"},
    {"country":"Qatar", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Quênia", "language":"Suaíli", "word":"Transgender"},
    {"country":"Reino Unido", "language":"Inglês", "word":"Transgender"},
    {"country":"República Dominicana", "language":"Espanhol", "word":"Transgénero"},
    {"country":"República Tcheca", "language":"Tcheco", "word":"Transsexuál"},
    {"country":"Romênia", "language":"Romeno", "word":"Transgender"},
    {"country":"Rússia", "language":"Russo", "word":"транссексуал"},
    {"country":"Senegal", "language":"Francês", "word":"Transgenre"},
    {"country":"Serra Leoa", "language":"Inglês", "word":"Transgender"},
    {"country":"Singapura", "language":"Inglês", "word":"Transgender"},
    {"country":"Síria", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Somália", "language":"Somali", "word":"Transgender"},
    {"country":"Sri Lanka", "language":"Sinhala", "word":"ප්‍රතිලේඛන"},
    {"country":"Suécia", "language":"Sueco", "word":"Transsexuell"},
    {"country":"Suíça", "language":"Alemão", "word":"Transgender"},
    {"country":"Tailândia", "language":"Tailandês", "word":"สาวประเภทสอง"},
    {"country":"Tanzânia", "language":"Suaíli", "word":"Transgender"},
    {"country":"Tunísia", "language":"Árabe", "word":"متحول جنسيا"},
    {"country":"Turquia", "language":"Turco", "word":"Transseksüel"},
    {"country":"Ucrânia", "language":"Ucraniano", "word":"транссексуал"},
    {"country":"Uganda", "language":"Inglês", "word":"Transgender"},
    {"country":"Uruguai", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Uzbequistão", "language":"Usbeque", "word":"Transgender"},
    {"country":"Venezuela", "language":"Espanhol", "word":"Transgénero"},
    {"country":"Vietnã", "language":"Vietnamita", "word":"Chuyển giới"},
    {"country":"Zâmbia", "language":"Inglês", "word":"Transgender"},
    {"country":"Zimbábue", "language":"Inglês", "word":"Transgender"}
];
